# docker-compose.yml

services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: AKMxt@747
      MYSQL_DATABASE: tasknest
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: AKMxt@747
      DB_DATABASE: tasknest
    volumes:
      - .:/app

volumes:
  db_data:
